/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        primary: '#002045',
        'primary-container': '#1a365d',
        'on-primary': '#ffffff',
        'on-primary-container': '#86a0cd',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#adc7f7',
        'on-primary-fixed': '#001b3c',
        'on-primary-fixed-variant': '#2d476f',
        'inverse-primary': '#adc7f7',
        secondary: '#545f72',
        'secondary-container': '#d5e0f7',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#586377',
        'secondary-fixed': '#d8e3fa',
        'secondary-fixed-dim': '#bcc7dd',
        'on-secondary-fixed': '#111c2c',
        'on-secondary-fixed-variant': '#3c475a',
        tertiary: '#002526',
        'tertiary-container': '#003d3e',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#61abac',
        'tertiary-fixed': '#a5eff0',
        'tertiary-fixed-dim': '#89d3d4',
        'on-tertiary-fixed': '#002020',
        'on-tertiary-fixed-variant': '#004f50',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f7fafc',
        'on-background': '#181c1e',
        surface: '#f7fafc',
        'surface-dim': '#d7dadc',
        'surface-bright': '#f7fafc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f6',
        'surface-container': '#ebeef0',
        'surface-container-high': '#e5e9eb',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#181c1e',
        'on-surface-variant': '#43474e',
        'surface-tint': '#455f88',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eef1f3',
        outline: '#74777f',
        'outline-variant': '#c4c6cf',
        'surface-variant': '#e0e3e5',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: { sans: ['Inter', 'sans-serif'] },
      maxWidth: { portal: '1280px' },
    },
  },
  plugins: [],
};
