apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: desc-portal
type: Opaque
stringData:
  MONGODB_URI: mongodb://mongodb:27017/desc_portal
  JWT_SECRET: desc_portal_super_secret_jwt_key_2024
  JWT_EXPIRE: 7d
  NODE_ENV: production
  CLIENT_URL: http://localhost:3000
  PORT: "5000"
